PasteLockly/urls.py
from django.urls import path
from PasteLockly import views
from django.conf import settings

app_name = 'PasteLockly'
urlpatterns = [
    path('pastelockly/',views.CreateSnippetView.as_view(), name='create_Snippet_Urls'),
    path('content/<int:pk>',views.RetriveSnippetView.as_view(), name='get_content'),
]

Shortly/urls.py
from django.urls import path
from Shortly import views
from django.conf import settings

app_name = 'Shortly'
urlpatterns = [
    path('short_url/',views.CreateShortUrlsView.as_view(), name='Create_Short_Urls'),
    path('short_url/<str:short_code>',views.PreviewShortUrlsView.as_view(), name='get_Short_Urls'),
]

WebScraper/urls.py
from django.urls import path
from WebScraper import views
from django.conf import settings

app_name = 'WebScraper'
urlpatterns = [
    path('get_html/',views.GetHtmlContentView.as_view(), name='create_Snippet_Urls'),
]

doqfy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shortly/',include('Shortly.urls')),
    path('pastelockly/',include('PasteLockly.urls')),
    path('webscraper/',include('WebScraper.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

PasteLockly/models.py
from django.db import models

class Snippet(models.Model):
    content = models.TextField()
    url = models.URLField(max_length=50, unique=True)
    secret_key = models.CharField(max_length=100, blank=True, null=True)
    encrypt = models.BooleanField(default = False)
    
    def __str__(self):
        return self.url
    class Meta:
        verbose_name_plural = "Snippet"

Shortly/models.py
from django.db import models

class Urls(models.Model):
    long_url = models.URLField(unique=True)
    short_url = models.CharField(max_length=20, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.long_url
    class Meta:
        verbose_name_plural = "Urls"

WebScraper/models.py
from django.db import models

# Create your models here.

PasteLockly/views.py
from django.shortcuts import render, redirect
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate
from rest_framework.reverse import reverse
from rest_framework import status
import json

# Models 
from PasteLockly.models import Snippet

# Serializers
from PasteLockly.serializers import SnippetSerializer

# Create your views here.
class CreateSnippetView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'urlshortener/snippet.html'
    
    def post(self, request, format=None): 
        serializer = SnippetSerializer(data=request.data)
        if serializer.is_valid():
            text = serializer.validated_data['content']
            unique_key = serializer.validated_data['secret_key']
            encrypt =False
            if unique_key:
                encrypt =True   
            text_obj = Snippet.objects.create(content=text, secret_key=unique_key, encrypt=encrypt)
            view1_url = reverse('PasteLockly:get_content',args=[text_obj.id])
            print("view1_url",view1_url)
            url = request.build_absolute_uri(view1_url)
            print("url", url)
            text_obj.url = url
            text_obj.save()
            return Response({'serializer':serializer},status=status.HTTP_201_CREATED)
        else:
            return Response({'message': ' Please fill vaild data'}, status = status.HTTP_400_BAD_REQUEST)
        
    def get (self,request):
        try:
            serializer = SnippetSerializer()
            return Response({'serializer': serializer})
        except Exception as e:
            return Response({'message': str(e)}, status = status.HTTP_400_BAD_REQUEST)
        
class RetriveSnippetView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'urlshortener/content.html'
    
    def get(self, request,pk,format=None):
        try:
            serializer = SnippetSerializer()
            snippet_obj = Snippet.objects.get(id=pk)
            if snippet_obj.encrypt == True:
                unique_key = request.GET.get('key')
                if unique_key == snippet_obj.secret_key:
                    return Response({'message':snippet_obj, 'serializer': serializer})
                else:   
                    return Response({'message': ' Invaild key'}, status = status.HTTP_400_BAD_REQUEST)
            else:
                return Response({'message':snippet_obj, 'serializer': serializer})
        except Exception as e:
            return Response({'message': str(e)}, status = status.HTTP_400_BAD_REQUEST)

Shortly/views.py
from django.shortcuts import render, redirect
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate
from rest_framework import status
from django.utils import timezone
import json

# Models 
from Shortly.models import Urls

#serializers
from Shortly.serializers import UrlSerializer

from Shortly.utils import generate_short_code

class CreateShortUrlsView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'urlshortener/Urls.html'
    
    def post(self, request):
        try:
            serializer = UrlSerializer(data=request.data)
            if serializer.is_valid():
                long_url = serializer.validated_data['long_url']
                short_code = generate_short_code()
                while Urls.objects.filter(short_url=short_code).exists():
                    short_code = generate_short_url()
                short_url = Urls.objects.create(long_url=long_url, short_url=short_code)
                return Response({'serializer': serializer, 'short_url': short_url},status=status.HTTP_201_CREATED)
            else:
                return Response({'message': ' Please fill vaild data'}, status = status.HTTP_400_BAD_REQUEST)
        except Exception as e:
            return Response({'message': str(e)}, status = status.HTTP_400_BAD_REQUEST)
        
    def get (self,request):
        try:
            serializer = UrlSerializer()
            return Response({'serializer': serializer})
        except Exception as e:
            return Response({'message': str(e)}, status = status.HTTP_400_BAD_REQUEST)

class PreviewShortUrlsView(APIView):
    def get (self,request,short_code):
        try:
            shortened_url = Urls.objects.get(short_url=short_code)
            if shortened_url:
                return HttpResponseRedirect(redirect_to=shortened_url.long_url)
            else:   
                return Response({'message': ' Url not found'}, status = status.HTTP_400_BAD_REQUEST)
        except Exception as e:
            return Response({'message': str(e)}, status = status.HTTP_400_BAD_REQUEST)

WebScraper/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate
from rest_framework.reverse import reverse
from rest_framework import status
import json

from WebScraper.tasks import get_table_data
class GetHtmlContentView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'urlshortener/htmltable.html'
    
    def get(self, request):
        webpage_url = 'https://www.nseindia.com/'
        obj = get_table_data.delay(webpage_url)
        return Response({'message':obj})

templates/urlshortener/Urls.html
{% load rest_framework %}

<!DOCTYPE html>
<html>
<head>
    <title>URL Shortener</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
    <h1>URL Shortener</h1>
    <form class="form-inline" action="{% url 'Shortly:Create_Short_Urls' %}" method="post">
        {% csrf_token %}
        {% render_form serializer %}

        <button type="submit" class="btn btn-default">Shorten URL</button>

    </form>
    {% if short_url %}
        <p>Short URL: <a href="{% url 'Shortly:get_Short_Urls' short_url.short_url %}">{{ short_url.short_url }}</a></p>
    {% endif %}
   
</body>
</html>

templates/urlshortener/content.html
{% load rest_framework %}

<!DOCTYPE html>
<html>
<head>
    <title>Snippet</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
    <h1>Snippet content</h1>
    <div class="container">
        <div>
            
            {% if message.content %}
                {{ message.content }}
            {% else %}
                {{ message}}
            {% endif %} 
        </div>
    </div>
</body>
</html>

templates/urlshortener/htmltable.html
{% load rest_framework %}

<!DOCTYPE html>
<html>
<head>
    <title>Snippet</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
    <h1>Snippet content</h1>
    <div class="container">
        <div>
            {% if message %}
                {{ message}}
            {% else %}
                {{ Error}}
            {% endif %} 
        </div>
    </div>
</body>
</html>

templates/urlshortener/sample.html
<!DOCTYPE html>
<html>
<head>
    <title>Snippet</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
    <h1>Snippet content</h1>
    <div class="container">
        <div>
            <table>
                <tr>
                    <th>no</th>
                    <th>name</th>
                    <th>age</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Sam</td>
                    <td>24</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Dhoni</td>
                    <td>42</td>
                </tr>
            </table>
        </div>
    </div>
</body>
</html>

templates/urlshortener/snippet.html
{% load rest_framework %}

<!DOCTYPE html>
<html>
<head>
    <title>Snippet</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
    <h1>Snippet</h1>
    <div class="container">
        <form class="" action="{% url 'PasteLockly:create_Snippet_Urls' %}" method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
                {% render_form serializer template_pack='rest_framework/vertical' %}

            <button type="submit" class="btn btn-default">Submit</button>

        </form>
    </div>
    {% comment %} {% if short_url %}
        <p>Short URL: <a href="{% url 'get_Short_Urls' short_url.short_url %}">{{ short_url.short_url }}</a></p>
    {% endif %} {% endcomment %}
   
</body>
</html>